# Use root/example as user/password credentials
version: '3.1'

services:

  server:
    build: .
    ports:
      - "8378:80"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 83Qn9]=32r.]X<Gt
