# Use root/example as user/password credentials
version: '3.1'

services:

  server:
    build: .
    ports:
      - "80:80"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '83Qn9]=32r.]X<Gt'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'test_password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./src/sql/initsql:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
